feat: add support for delete command
wildbit/postmark-cli pull request #82
Opened 2023-09-30 06:21 UTC by rlueder

**NOTE** This will delete ALL templates (except Layouts) of the server you supply the token for. Use at your own risk.

This is a really basic implementation of a delete command but solves my use case which is to not have to manually delete every template on my server.

2024-01-23 20:19 UTC, rlueder commented
@derekrushforth  @tomek-ac just checking in on this PR, I used it again a couple of weeks ago and it worked pretty well. Would love to have this be part of the library instead of having to run my own fork. Let me know if you need anything else to get this merged. Thanks!

2024-02-01 03:11 UTC, tomek-ac requested changes
Thanks for working on this @rlueder! I left a few suggestions for you to consider.
Besides that here is a few other things that would need to be addressed before merging: 
- the delete command can be run in non-interactive mode in CI/CD 
- we have integration tests for this code
- the "delete" command is listed when running `postmark templates`
- we will need to update our wiki to explain how to use it. For this please prepare a separate Markdown file as part of the PR.

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +
```suggestion
```

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +
```suggestion
```

This doesn't add much, the code is self-explanatory.

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +    // against ids/aliases that exist in the server
I'd say we don't need to validate that. Ideally running the command with a non-existing ID should display a warning.

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +
```suggestion
```
again, the code is self-explanatory. Comments are most valuable when they explain the "why" leaving the "what" to the code.

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +      validate: validateUserInput,
Maybe we could inline the validation if it's so simple?

```suggestion
      validate: (s) => s.trim().length > 0, // don't allow empty input
```

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +    }
we could inline the validation here too:

```suggestion
    if (confirmed) {
      inputIsValid = await input({
        message: 'Enter "delete all templates" to confirm:',
        validate: (s) => s === 'delete all templates',
      });
    }
```

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +        message: `Delete ALL templates? Are you sure?`,
```suggestion
        message: 'Delete ALL templates? Are you sure?',
```

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +      return fatalError("There are no templates on this server.");
We probably shouldn't exit with an error if there are no templates on the server. I guess this would only happen if the user requested to delete all the servers. In such case the user's intention is to not have templates so when there are not any, then we should be good.

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +      });
In 99% of the cases we would get all the templates with this call as Postmark allows for 100 templates per Server by default. But to make it a bit more resilient and correct, we should fetch _all_ the templates, not the only first batch. We'd need a loop to fill the `templates` array.

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +    let totalCount = 0;
Can't we use `templates.length` instead of adding another variable?

2024-02-01 03:11 UTC, tomek-ac commented on src/commands/templates/delete.ts
> +
Please follow the local conventions.

```suggestion
```

2024-07-13 02:57 UTC, closed without merging